'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Proect_Work.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _NEW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NEW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ADD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ADD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property akshay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("akshay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Backgound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Backgound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btn_back_static() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn-back-static", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btn_next_static() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn-next-static", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btn_previous_static() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn-previous-static", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CANCEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CANCEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DELETE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DELETE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Heart_SelectionSubpicture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Heart_SelectionSubpicture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Heart_VideoInset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Heart_VideoInset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property light_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("light_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MI1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MI1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MI2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MI2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NavigationLeft_SelectionSubpicture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavigationLeft_SelectionSubpicture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NavigationRight_ButtonGraphic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavigationRight_ButtonGraphic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NavigationRight_SelectionSubpicture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavigationRight_SelectionSubpicture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NavigationUp_ButtonGraphic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavigationUp_ButtonGraphic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NavigationUp_SelectionSubpicture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavigationUp_SelectionSubpicture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NextMenuButtonIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NextMenuButtonIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Notes_btn_back_static() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Notes_btn-back-static", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ParentMenuButtonIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ParentMenuButtonIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pets_btn_back_static() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pets_btn-back-static", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pets_btn_next_static() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pets_btn-next-static", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pets_btn_previous_static() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pets_btn-previous-static", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PreviousMenuButtonIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PreviousMenuButtonIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Recycle_Bin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Recycle Bin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SAVE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SAVE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wmpnss_color120() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wmpnss_color120", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
